# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  access_key = ENV['AWS_ACCESS_KEY']
  access_secret = ENV['AWS_SECRET_KEY']
  private_key_path = ENV['PRIVATE_KEY_PATH'] 
  keypair_name = ENV['AWS_KEYPAIR_NAME']
  subnet_id = ENV['AWS_SUBNET_ID']

  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"


  config.vm.define :node do |node|
    node.vm.provider :aws do |aws, override|
      aws.access_key_id = access_key
      aws.secret_access_key = access_secret
      aws.keypair_name = keypair_name
      aws.region = "ap-northeast-1"
      aws.ami = "ami-2199d511"
      aws.user_data = "#!/bin/bash\nexport TARGET_ENV=test;"
      aws.availability_zone = "ap-northeast-1a"
      aws.instance_type = "t2.micro"
      aws.security_groups = ["ssh_and_http"]
      override.ssh.username = "aws_user"
      override.ssh.private_key_path = private_key_path
      aws.associate_public_ip = 'true'
      aws.subnet_id = subnet_id
      aws.tags = {
        'Name' => 'node',
      }
    end
    #node.vm.provision "ansible" do |ansible|
    #  ansible.groups = {
    #    "node" => ["node"]
    #  }
    #  ansible.extra_vars = {
    #    "db_host" => db_host,
    #    "db_name" => "db_01"
    #  }
    #  ansible.playbook = "playbook.yml"
    #end
  end

#  config.vm.define :ap2 do |ap2|
#    ap2.vm.provider :aws do |aws, override|
#      aws.access_key_id = access_key
#      aws.secret_access_key = access_secret
#      aws.keypair_name = "AWS_KEYPAIR_NAME"
#      aws.region = "ap-northeast-1"
#      aws.ami = "ami-xxxxxx"
#      aws.user_data = "#!/bin/bash\nexport TARGET_ENV=test;"
#      aws.availability_zone = "ap-northeast-1a"
#      aws.instance_type = "m1.small"
#      aws.security_groups = ["aws_security_group"]
#      override.ssh.username = "aws_user"
#      override.ssh.private_key_path = "~/.ssh/aws_private_key"
#      aws.tags = {
#        'Name' => 'ap02',
#      }
#    end
#    ap2.vm.provision "ansible" do |ansible|
#      ansible.groups = {
#        "ap2" => ["ap2"]
#      }
#      ansible.extra_vars = {
#        "db_host" => db_host,
#        "db_name" => "db_02"
#      }
#      ansible.playbook = "playbook.yml"
#    end
#  end
#
#  config.vm.define :ap3 do |ap3|
#    ap3.vm.provider :aws do |aws, override|
#      aws.access_key_id = access_key
#      aws.secret_access_key = access_secret
#      aws.keypair_name = "AWS_KEYPAIR_NAME"
#      aws.region = "ap-northeast-1"
#      aws.ami = "ami-xxxxxx"
#      aws.user_data = "#!/bin/bash\nexport TARGET_ENV=test;"
#      aws.availability_zone = "ap-northeast-1a"
#      aws.instance_type = "m1.small"
#      aws.security_groups = ["aws_security_group"]
#      override.ssh.username = "aws_user"
#      override.ssh.private_key_path = "~/.ssh/aws_private_key"
#      aws.tags = {
#        'Name' => 'ap03',
#      }
#    end
#    ap3.vm.provision "ansible" do |ansible|
#      ansible.groups = {
#        "ap3" => ["ap3"]
#      }
#      ansible.extra_vars = {
#        "db_host" => db_host,
#        "db_name" => "db_03"
#      }
#      ansible.playbook = "playbook.yml"
#    end
#  end
#
#  config.vm.define :ap4 do |ap4|
#    ap4.vm.provider :aws do |aws, override|
#      aws.access_key_id = access_key
#      aws.secret_access_key = access_secret
#      aws.keypair_name = "AWS_KEYPAIR_NAME"
#      aws.region = "ap-northeast-1"
#      aws.ami = "ami-xxxxxx"
#      aws.user_data = "#!/bin/bash\nexport TARGET_ENV=test;"
#      aws.availability_zone = "ap-northeast-1a"
#      aws.instance_type = "m1.small"
#      aws.security_groups = ["aws_security_group"]
#      override.ssh.username = "aws_user"
#      override.ssh.private_key_path = "~/.ssh/aws_private_key"
#      aws.tags = {
#        'Name' => 'ap04',
#      }
#    end
#    ap4.vm.provision "ansible" do |ansible|
#      ansible.groups = {
#        "ap4" => ["ap4"]
#      }
#      ansible.extra_vars = {
#        "db_host" => db_host,
#        "db_name" => "db_04"
#      }
#      ansible.playbook = "playbook.yml"
#    end
#  end
#
#  config.vm.define :ap5 do |ap5|
#    ap5.vm.provider :aws do |aws, override|
#      aws.access_key_id = access_key
#      aws.secret_access_key = access_secret
#      aws.keypair_name = "AWS_KEYPAIR_NAME"
#      aws.region = "ap-northeast-1"
#      aws.ami = "ami-xxxxxx"
#      aws.user_data = "#!/bin/bash\nexport TARGET_ENV=test;"
#      aws.availability_zone = "ap-northeast-1a"
#      aws.instance_type = "m1.small"
#      aws.security_groups = ["aws_security_group"]
#      override.ssh.username = "aws_user"
#      override.ssh.private_key_path = "~/.ssh/aws_private_key"
#      aws.tags = {
#        'Name' => 'ap05',
#      }
#    end
#    ap5.vm.provision "ansible" do |ansible|
#      ansible.groups = {
#        "ap5" => ["ap5"]
#      }
#      ansible.extra_vars = {
#        "db_host" => db_host,
#        "db_name" => "db_05"
#      }
#      ansible.playbook = "playbook.yml"
#    end
#  end

end
