VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65-x86_64-20140116"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.ssh.forward_agent = true

  config.vm.define :node1 do |node|
    node.vm.box = "centOS65Box"
    node.vm.network :forwarded_port, guest:22, host:2071, id:"ssh"
    node.vm.network :forwarded_port, guest:80, host:8151, id:"http"
    node.vm.network :private_network, ip:"192.168.33.81"
  end

  config.vm.define :node2 do |node|
    node.vm.box = "centOS65Box"
    node.vm.network :forwarded_port, guest:22, host:2072, id:"ssh"
    node.vm.network :forwarded_port, guest:80, host:8152, id:"http"
    node.vm.network :private_network, ip:"192.168.33.82"
  end

end
